import { motion } from 'framer-motion';
import { aboutData } from '../../data/portfolioData';

// Responsive images (generated by scripts/process-profile-image.js)
// If you haven't generated responsive variants yet, fall back to the single image.
import profile1080 from '../../assets/portfolio_image_vignesh_g.jpg';

const fadeUp = (delay = 0) => ({
  initial:     { opacity: 0, y: 24 },
  whileInView: { opacity: 1, y: 0  },
  viewport:    { once: true, margin: '-60px' },
  transition:  { duration: 0.55, ease: [0.4, 0, 0.2, 1], delay },
});

export default function About() {
  const { img, paragraphs, quote, skillsByCategory } = aboutData;

  return (
    <section id="about" className="section">
      <div className="container">
        <motion.p className="section__eyebrow" {...fadeUp(0)}>About</motion.p>
        <motion.h2 className="section__title" {...fadeUp(0.08)}>
          The person behind the code
        </motion.h2>

        <div className="about__grid">
          {/* Image column */}
          <motion.div className="about__photo-col" {...fadeUp(0.1)}>
            <div className="about__img-wrap" data-label="Vignesh G — MERN Stack">
              <img
                src={profile1080}
                alt="Vignesh G"
                loading="lazy"
              />
            </div>
            {/* Top skills preview */}
            <div className="about__stack-preview">
              {['React', 'Node.js', 'MongoDB', 'Express', 'Next.js'].map(s => (
                <span key={s} className="chip chip--accent">{s}</span>
              ))}
            </div>
          </motion.div>

          {/* Text column */}
          <div className="about__text-col">
            {paragraphs.map((p, i) => (
              <motion.p key={i} className="about__p" {...fadeUp(0.1 + i * 0.07)}>
                {p}
              </motion.p>
            ))}
            <motion.blockquote className="about__quote" {...fadeUp(0.32)}>
              {quote}
            </motion.blockquote>

            {/* Skills grouped */}
            <motion.div className="about__skills-section" {...fadeUp(0.38)}>
              {skillsByCategory.map((group) => (
                <div key={group.category} className="about__skills-row">
                  <span className="about__category-label">{group.category}</span>
                  <div className="about__chips">
                    {group.skills.map(s => (
                      <span key={s} className="chip">{s}</span>
                    ))}
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}
